### ISSUE TITLE
OpenAPI files?

### ISSUE THREAD

**Issue by NKnusperer** [adsk-duszykf/Adsk.Platform.Toolkit#1]
Hello, can you provide the OpenAPI files that are used as the Kiota input, for example:
https://github.com/adsk-duszykf/Adsk.Platform.Toolkit/blob/6ab2501c8555581ad9d8df4146d3a9977468b501/Autodesk.ACC.RFIs/GeneratedCode/kiota-lock.json#L3

Thank you.

**Comment by adsk-duszykf** [comment]
Hi, unfortunately, I cannot share those files.

**Comment by adsk-duszykf** [comment]
Hi, few official Open API specifications have been published here: https://github.com/autodesk-platform-services/aps-sdk-openapi
