### ISSUE TITLE
Support for ACC / BIM 360 Issues API

### ISSUE THREAD

**Issue by NKnusperer** [adsk-duszykf/Adsk.Platform.Toolkit#2]
Hello, can you add support for the [BIM 360 Issues-V2 (new)](https://aps.autodesk.com/en/docs/bim360/v1/reference/http/issues-v2-issues-GET/) and [ACC Issues](https://aps.autodesk.com/en/docs/acc/v1/reference/http/issues-issues-GET/) API?

Thank you.

**Comment by adsk-duszykf** [comment]
ACC Issues are now available [here](https://www.nuget.org/packages/Adsk.Platform.ACC.Issues/)
