### ISSUE TITLE
`RfiPriority` does not parse value

### ISSUE THREAD

**Issue by NKnusperer** [adsk-duszykf/Adsk.Platform.Toolkit#3]
Hello,
currently `RfiPriority` does not parse the actual value, instead it is always just an empty instance..
https://github.com/adsk-duszykf/Adsk.Platform.Toolkit/blob/b7651bfdea23ff550020b5725fb996526ec627dc/Autodesk.ACC.RFIs/GeneratedCode/Models/RfiPriority.cs#L23

**Comment by adsk-duszykf** [comment]
Thank you for your feedback. The issue has been fixed: [0.0.14](https://www.nuget.org/packages/Adsk.Platform.ACC.RFIs/0.0.14)
