### ISSUE TITLE
`RfiBase` is missing `question` and `dueDate`

### ISSUE THREAD

**Issue by NKnusperer** [adsk-duszykf/Adsk.Platform.Toolkit#4]
Following up to #3 I noticed that `question`, `dueDate` and probably some other properties are missing for RFIs.
They can not be set via `CreateRfiRequest` too.

**Comment by adsk-duszykf** [comment]
Fix here: [0.0.16](https://www.nuget.org/packages/Adsk.Platform.ACC.RFIs/0.0.16)
